export const locationData = {
    "Gujarat": {
        "Ahmedabad": ["Ahmedabad APMC", "Daskroi APMC", "Dholka APMC", "Bavla APMC", "Sanand APMC", "Viramgam APMC"],
        "Amreli": ["Amreli APMC", "Babra APMC", "Bagasara APMC", "Dhari APMC", "Jafrabad APMC", "Kunkavav APMC", "Lathi APMC", "Rajula APMC", "Savarkundla APMC"],
        "Anand": ["Anand APMC", "Anklav APMC", "Borsad APMC", "Khambhat APMC", "Petlad APMC", "Tarapur APMC", "Umreth APMC"],
        "Aravalli": ["Bayad APMC", "Bhiloda APMC", "Dhansura APMC", "Malpur APMC", "Meghraj APMC", "Modasa APMC"],
        "Banaskantha": ["Palanpur APMC", "Amirgadh APMC", "Bhabhar APMC", "Danta APMC", "Dantiwada APMC", "Deesa APMC", "Deodar APMC", "Dhanera APMC", "Kankrej APMC", "Lakhani APMC", "Santalpur APMC", "Tharad APMC", "Vadgam APMC", "Vav APMC"],
        "Bharuch": ["Bharuch APMC", "Amod APMC", "Ankleshwar APMC", "Hansot APMC", "Jambusar APMC", "Jhagadia APMC", "Netrang APMC", "Vagra APMC"],
        "Bhavnagar": ["Bhavnagar APMC", "Botad APMC", "Gadhada APMC", "Gariadhar APMC", "Ghogha APMC", "Mahuva APMC", "Palitana APMC", "Sihor APMC", "Talaja APMC", "Umrala APMC", "Vallabhipur APMC"],
        "Botad": ["Botad APMC", "Barvala APMC", "Gadhada APMC", "Ranpur APMC"],
        "Chhota Udaipur": ["Chhota Udaipur APMC", "Bodeli APMC", "Jetpur Pavi APMC", "Kavant APMC", "Nasvadi APMC", "Sankheda APMC"],
        "Dahod": ["Dahod APMC", "Devgadh Baria APMC", "Dhanpur APMC", "Fatepura APMC", "Garbada APMC", "Jhalod APMC", "Limkheda APMC", "Sanjeli APMC", "Singvad APMC"],
        "Dang": ["Ahwa APMC", "Subir APMC", "Waghai APMC"],
        "Devbhoomi Dwarka": ["Khambhalia APMC", "Bhanvad APMC", "Dwarka APMC", "Kalyanpur APMC", "Okha APMC"],
        "Gandhinagar": ["Gandhinagar APMC", "Dehgam APMC", "Kalol APMC", "Mansa APMC"],
        "Gir Somnath": ["Veraval APMC", "Kodinar APMC", "Sutrapada APMC", "Talala APMC", "Una APMC"],
        "Jamnagar": ["Jamnagar APMC", "Dhrol APMC", "Jodiya APMC", "Kalavad APMC", "Kalyanpur APMC", "Jamjodhpur APMC", "Lalpur APMC"],
        "Junagadh": ["Junagadh APMC", "Bhesan APMC", "Keshod APMC", "Malia APMC", "Manavadar APMC", "Mangrol APMC", "Mendarda APMC", "Vanthali APMC", "Visavadar APMC"],
        "Kheda": ["Kheda APMC", "Kapadvanj APMC", "Kathlal APMC", "Mahudha APMC", "Matar APMC", "Nadiad APMC", "Thasra APMC", "Vaso APMC"],
        "Kutch": ["Bhuj APMC", "Abdasa APMC", "Anjar APMC", "Bhachau APMC", "Gandhidham APMC", "Mandvi APMC", "Mundra APMC", "Nakhatrana APMC", "Rapar APMC"],
        "Mahisagar": ["Lunawada APMC", "Balasinor APMC", "Kadana APMC", "Khanpur APMC", "Santrampur APMC", "Virpur APMC"],
        "Mehsana": ["Mehsana APMC", "Becharaji APMC", "Jotana APMC", "Kadi APMC", "Kheralu APMC", "Satlasana APMC", "Unjha APMC", "Vadnagar APMC", "Vijapur APMC", "Visnagar APMC"],
        "Morbi": ["Morbi APMC", "Halvad APMC", "Maliya APMC", "Tankara APMC", "Wankaner APMC"],
        "Narmada": ["Rajpipla APMC", "Dediapada APMC", "Garudeshwar APMC", "Nandod APMC", "Sagbara APMC", "Tilakwada APMC"],
        "Navsari": ["Navsari APMC", "Chikhli APMC", "Gandevi APMC", "Jalalpore APMC", "Khergam APMC", "Vansda APMC"],
        "Panchmahal": ["Godhra APMC", "Ghoghamba APMC", "Halol APMC", "Jambughoda APMC", "Kalol APMC", "Morva Hadaf APMC", "Shahera APMC"],
        "Patan": ["Patan APMC", "Chanasma APMC", "Harij APMC", "Radhanpur APMC", "Sami APMC", "Santalpur APMC", "Saraswati APMC", "Sidhpur APMC"],
        "Porbandar": ["Porbandar APMC", "Kutiyana APMC", "Ranavav APMC"],
        "Rajkot": ["Rajkot APMC", "Dhoraji APMC", "Gondal APMC", "Jasdan APMC", "Jetpur APMC", "Kotda Sangani APMC", "Lodhika APMC", "Paddhari APMC", "Upleta APMC", "Vinchhiya APMC"],
        "Sabarkantha": ["Himmatnagar APMC", "Idar APMC", "Khedbrahma APMC", "Prantij APMC", "Talod APMC", "Vadali APMC", "Vijaynagar APMC"],
        "Surat": ["Surat APMC", "Bardoli APMC", "Choryasi APMC", "Kamrej APMC", "Mahuva APMC", "Mandvi APMC", "Mangrol APMC", "Olpad APMC", "Palsana APMC", "Umarpada APMC"],
        "Surendranagar": ["Surendranagar APMC", "Chuda APMC", "Dasada APMC", "Dhrangadhra APMC", "Lakhtar APMC", "Limbdi APMC", "Muli APMC", "Sayla APMC", "Thangadh APMC", "Wadhwan APMC"],
        "Tapi": ["Vyara APMC", "Dolvan APMC", "Kukarmunda APMC", "Nizar APMC", "Songadh APMC", "Uchchhal APMC", "Valod APMC"],
        "Vadodara": ["Vadodara APMC", "Dabhoi APMC", "Karjan APMC", "Padra APMC", "Savli APMC", "Shinor APMC", "Waghodia APMC"],
        "Valsad": ["Valsad APMC", "Dharampur APMC", "Kaprada APMC", "Pardi APMC", "Umbergaon APMC", "Vapi APMC"]
    },
    "Maharashtra": {
        "Ahmednagar": ["Ahmednagar APMC", "Rahata APMC", "Kopargaon APMC", "Shrirampur APMC", "Sangamner APMC", "Akole APMC", "Jamkhed APMC", "Karjat APMC", "Newasa APMC", "Pathardi APMC", "Rahuri APMC", "Shevgaon APMC", "Shrigonda APMC"],
        "Akola": ["Akola APMC", "Murtizapur APMC", "Akot APMC", "Balapur APMC", "Telhara APMC", "Patur APMC", "Barshitakli APMC"],
        "Amravati": ["Amravati APMC", "Morshi APMC", "Warud APMC", "Daryapur APMC", "Achalpur APMC", "Anjangaon Surji APMC", "Chandur Railway APMC", "Dhamangaon APMC", "Nandgaon Khandeshwar APMC", "Teosa APMC"],
        "Aurangabad": ["Aurangabad APMC", "Paithan APMC", "Vaijapur APMC", "Lasur APMC", "Gangapur APMC", "Kannad APMC", "Khultabad APMC", "Phulambri APMC", "Sillod APMC", "Soygaon APMC"],
        "Beed": ["Beed APMC", "Ambejogai APMC", "Ashti APMC", "Georai APMC", "Kaij APMC", "Majalgaon APMC", "Parli Vaijnath APMC", "Patoda APMC"],
        "Bhandara": ["Bhandara APMC", "Lakhandur APMC", "Lakhani APMC", "Mohadi APMC", "Pauni APMC", "Sakoli APMC", "Tumsar APMC"],
        "Buldhana": ["Buldhana APMC", "Chikhli APMC", "Deulgaon Raja APMC", "Jalgaon Jamod APMC", "Khamgaon APMC", "Lonar APMC", "Malkapur APMC", "Mehkar APMC", "Nandura APMC", "Shegaon APMC"],
        "Chandrapur": ["Chandrapur APMC", "Bhadrawati APMC", "Bramhapuri APMC", "Chimur APMC", "Gondpipri APMC", "Mul APMC", "Nagbhir APMC", "Rajura APMC", "Sindewahi APMC", "Warora APMC"],
        "Dhule": ["Dhule APMC", "Dondaicha APMC", "Sakri APMC", "Shirpur APMC"],
        "Gadchiroli": ["Gadchiroli APMC", "Aheri APMC", "Armori APMC", "Chamorshi APMC", "Sironcha APMC"],
        "Gondia": ["Gondia APMC", "Amgaon APMC", "Arjuni Morgaon APMC", "Deori APMC", "Goregaon APMC", "Sadak Arjuni APMC", "Salekasa APMC", "Tirora APMC"],
        "Hingoli": ["Hingoli APMC", "Basmath APMC", "Kalamnuri APMC", "Sengaon APMC"],
        "Jalgaon": ["Jalgaon APMC", "Bhusawal APMC", "Chalisgaon APMC", "Pachora APMC", "Amalner APMC", "Bhadgaon APMC", "Bodwad APMC", "Chopda APMC", "Dharangaon APMC", "Erandol APMC", "Jamner APMC", "Parola APMC", "Raver APMC", "Yawal APMC"],
        "Jalna": ["Jalna APMC", "Ambad APMC", "Bhokardan APMC", "Ghansawangi APMC", "Jafrabad APMC", "Mantha APMC", "Partur APMC"],
        "Kolhapur": ["Kolhapur APMC", "Gadhinglaj APMC", "Jaysingpur APMC", "Malkapur APMC", "Vadgaon Peth APMC"],
        "Latur": ["Latur APMC", "Udgir APMC", "Ahmedpur APMC", "Ausa APMC", "Chakur APMC", "Deoni APMC", "Jalkot APMC", "Nilanga APMC", "Renapur APMC", "Shirur Anantpal APMC"],
        "Mumbai": ["Mumbai APMC (Vashi)", "Kalyan APMC", "Panvel APMC", "Pen APMC", "Karjat APMC", "Khalapur APMC", "Mangaon APMC", "Roha APMC", "Alibag APMC", "Murud APMC"],
        "Nagpur": ["Nagpur APMC", "Kamptee APMC", "Katol APMC", "Saoner APMC", "Ramtek APMC", "Bhiwapur APMC", "Hingna APMC", "Kalmeshwar APMC", "Kuhi APMC", "Mauda APMC", "Narkhed APMC", "Parseoni APMC", "Umred APMC"],
        "Nanded": ["Nanded APMC", "Loha APMC", "Bhokar APMC", "Biloli APMC", "Deglur APMC", "Dharmabad APMC", "Hadgaon APMC", "Himayatnagar APMC", "Kandhar APMC", "Kinwat APMC", "Mukhed APMC", "Naigaon APMC"],
        "Nandurbar": ["Nandurbar APMC", "Navapur APMC", "Shahada APMC", "Taloda APMC", "Akkalkuwa APMC"],
        "Nashik": ["Nashik APMC", "Lasalgaon APMC", "Pimpalgaon APMC", "Sinnar APMC", "Yeola APMC", "Chandwad APMC", "Deola APMC", "Dindori APMC", "Igatpuri APMC", "Kalwan APMC", "Malegaon APMC", "Nandgaon APMC", "Niphad APMC", "Satana APMC"],
        "Osmanabad": ["Osmanabad APMC", "Bhoom APMC", "Kalamb APMC", "Murum APMC", "Omerga APMC", "Paranda APMC", "Tuljapur APMC", "Washi APMC"],
        "Parbhani": ["Parbhani APMC", "Bori APMC", "Gangakhed APMC", "Jintur APMC", "Manwath APMC", "Palam APMC", "Pathri APMC", "Purna APMC", "Sailu APMC", "Sonpeth APMC"],
        "Pune": ["Pune APMC", "Manchar APMC", "Junnar APMC", "Baramati APMC", "Indapur APMC", "Bhor APMC", "Daund APMC", "Khed APMC", "Lonawala APMC", "Mulshi APMC", "Saswad APMC", "Shirur APMC", "Velhe APMC"],
        "Raigad": ["Pen APMC", "Karjat APMC", "Khalapur APMC", "Mangaon APMC", "Roha APMC", "Alibag APMC", "Mahad APMC", "Murud APMC", "Panvel APMC"],
        "Ratnagiri": ["Ratnagiri APMC", "Chiplun APMC", "Dapoli APMC", "Khed APMC", "Rajapur APMC", "Sangameshwar APMC"],
        "Sangli": ["Sangli APMC", "Tasgaon APMC", "Vita APMC", "Islampur APMC", "Atpadi APMC", "Jat APMC", "Palus APMC", "Shirala APMC"],
        "Satara": ["Satara APMC", "Karad APMC", "Phaltan APMC", "Wai APMC", "Koregaon APMC", "Lonand APMC", "Mahabaleshwar APMC", "Patan APMC", "Vaduj APMC"],
        "Sindhudurg": ["Sawantwadi APMC", "Kankavli APMC", "Kudal APMC", "Vengurla APMC"],
        "Solapur": ["Solapur APMC", "Pandharpur APMC", "Akluj APMC", "Barshi APMC", "Kurduwadi APMC", "Akkalkot APMC", "Karmala APMC", "Mangalwedha APMC", "Mohol APMC", "Sangola APMC"],
        "Thane": ["Thane APMC", "Kalyan APMC", "Murbad APMC", "Shahapur APMC", "Ulhasnagar APMC", "Bhiwandi APMC"],
        "Wardha": ["Wardha APMC", "Arvi APMC", "Ashti APMC", "Hinganghat APMC", "Pulgaon APMC", "Samudrapur APMC", "Seloo APMC", "Sindi APMC"],
        "Washim": ["Washim APMC", "Karanj APMC", "Malegaon APMC", "Mangrulpir APMC", "Manora APMC", "Risod APMC"],
        "Yavatmal": ["Yavatmal APMC", "Arni APMC", "Babulgaon APMC", "Darwha APMC", "Digras APMC", "Ghatanji APMC", "Kalamb APMC", "Mahagaon APMC", "Maregaon APMC", "Ner APMC", "Pandharkawada APMC", "Pusad APMC", "Ralegaon APMC", "Umarkhed APMC", "Wani APMC", "Zari Jamani APMC"]
    },
    "Rajasthan": {
        "Ajmer": ["Ajmer APMC", "Beawar APMC", "Kishangarh APMC", "Bijainagar APMC", "Kekri APMC", "Nasirabad APMC", "Pisangan APMC"],
        "Alwar": ["Alwar APMC", "Khairthal APMC", "Kherli APMC", "Rajgarh APMC", "Ramgarh APMC", "Tijara APMC"],
        "Banswara": ["Banswara APMC", "Kushalgarh APMC"],
        "Baran": ["Baran APMC", "Anta APMC", "Atru APMC", "Chhabra APMC", "Chhipabarod APMC"],
        "Barmer": ["Barmer APMC", "Balotra APMC", "Gudamalani APMC", "Siwana APMC"],
        "Bharatpur": ["Bharatpur APMC", "Bayana APMC", "Nadbai APMC", "Deeg APMC", "Kaman APMC", "Nagar APMC", "Weir APMC"],
        "Bhilwara": ["Bhilwara APMC", "Gulabpura APMC", "Jahazpur APMC", "Kotri APMC", "Mandalgarh APMC", "Shahpura APMC"],
        "Bikaner": ["Bikaner APMC", "Nokha APMC", "Khajuwala APMC", "Dungargarh APMC", "Lunkaransar APMC"],
        "Bundi": ["Bundi APMC", "Dei APMC", "Keshoraipatan APMC", "Nainwa APMC"],
        "Chittorgarh": ["Chittorgarh APMC", "Begun APMC", "Kapasan APMC", "Nimbahera APMC", "Pratapgarh APMC"],
        "Churu": ["Churu APMC", "Rajgarh APMC", "Ratangarh APMC", "Sardarsahar APMC", "Sujangarh APMC"],
        "Dausa": ["Dausa APMC", "Bandikui APMC", "Lalsot APMC", "Mahwa APMC"],
        "Dholpur": ["Dholpur APMC", "Badi APMC"],
        "Dungarpur": ["Dungarpur APMC", "Sagwara APMC"],
        "Ganganagar": ["Sri Ganganagar APMC", "Padampur APMC", "Raisinghnagar APMC", "Sadulshahar APMC", "Suratgarh APMC", "Gajsinghpur APMC", "Karanpur APMC", "Vijaynagar APMC"],
        "Hanumangarh": ["Hanumangarh APMC", "Nohar APMC", "Bhadra APMC", "Sangaria APMC", "Pilibanga APMC", "Rawatsar APMC"],
        "Jaipur": ["Jaipur APMC (Muhana)", "Chomu APMC", "Chaksu APMC", "Kotputli APMC", "Shahpura APMC", "Bassi APMC", "Dudu APMC", "Phulera APMC", "Renwal APMC", "Sambhar APMC"],
        "Jaisalmer": ["Jaisalmer APMC", "Pokaran APMC"],
        "Jalore": ["Jalore APMC", "Bhinmal APMC", "Raniwara APMC", "Sanchore APMC"],
        "Jhalawar": ["Jhalawar APMC", "Aklera APMC", "Bhawani Mandi APMC", "Khanpur APMC", "Pirawa APMC"],
        "Jhunjhunu": ["Jhunjhunu APMC", "Chirawa APMC", "Nawalgarh APMC", "Surajgarh APMC"],
        "Jodhpur": ["Jodhpur APMC", "Bilara APMC", "Phalodi APMC", "Piparcity APMC", "Bhopalgarh APMC", "Osian APMC"],
        "Karauli": ["Karauli APMC", "Hindaun APMC", "Todabhim APMC"],
        "Kota": ["Kota APMC", "Ramganj Mandi APMC", "Itawa APMC", "Sangod APMC", "Sultanpur APMC"],
        "Nagaur": ["Nagaur APMC", "Merta City APMC", "Kuchaman City APMC", "Degana APMC", "Didwana APMC", "Jayal APMC", "Ladnun APMC", "Parbatsar APMC"],
        "Pali": ["Pali APMC", "Bali APMC", "Falna APMC", "Jaitaran APMC", "Rani APMC", "Sojat Road APMC", "Sumerpur APMC"],
        "Rajsamand": ["Rajsamand APMC", "Amet APMC", "Bhim APMC", "Deogarh APMC", "Nathdwara APMC"],
        "Sawai Madhopur": ["Sawai Madhopur APMC", "Gangapur City APMC"],
        "Sikar": ["Sikar APMC", "Fatehpur APMC", "Neem Ka Thana APMC", "Sri Madhopur APMC"],
        "Sirohi": ["Sirohi APMC", "Abu Road APMC", "Pindwara APMC", "Reodar APMC", "Sheoganj APMC"],
        "Tonk": ["Tonk APMC", "Deoli APMC", "Malpura APMC", "Niwai APMC", "Uniyara APMC"],
        "Udaipur": ["Udaipur APMC", "Fatehnagar APMC"]
    },
    "Madhya Pradesh": {
        "Agar Malwa": ["Agar APMC", "Nalkheda APMC", "Susner APMC"],
        "Alirajpur": ["Alirajpur APMC", "Jobat APMC"],
        "Anuppur": ["Anuppur APMC", "Kotma APMC"],
        "Ashoknagar": ["Ashoknagar APMC", "Chanderi APMC", "Mungaoli APMC", "Piprai APMC"],
        "Balaghat": ["Balaghat APMC", "Katangi APMC", "Lalburra APMC", "Waraseoni APMC"],
        "Barwani": ["Barwani APMC", "Anjad APMC", "Khetia APMC", "Sendhwa APMC"],
        "Betul": ["Betul APMC", "Multai APMC"],
        "Bhind": ["Bhind APMC", "Gohad APMC", "Lahar APMC", "Mehgaon APMC"],
        "Bhopal": ["Bhopal APMC (Karond)", "Berasia APMC"],
        "Burhanpur": ["Burhanpur APMC"],
        "Chhatarpur": ["Chhatarpur APMC", "Harpalpur APMC", "Lavkushnagar APMC", "Nowgong APMC"],
        "Chhindwara": ["Chhindwara APMC", "Amarwara APMC", "Chaurai APMC", "Pandhurna APMC", "Parasia APMC", "Sausar APMC"],
        "Damoh": ["Damoh APMC", "Hatta APMC", "Patharia APMC"],
        "Datia": ["Datia APMC", "Sevda APMC"],
        "Dewas": ["Dewas APMC", "Sonkatch APMC", "Kannod APMC", "Khategaon APMC", "Bagli APMC", "Hatpipliya APMC", "Loharda APMC"],
        "Dhar": ["Dhar APMC", "Badnawar APMC", "Kukshi APMC", "Manawar APMC", "Dhamnod APMC", "Gandhwani APMC", "Rajgarh APMC"],
        "Dindori": ["Dindori APMC"],
        "Guna": ["Guna APMC", "Aron APMC", "Binaganj APMC", "Kumbhraj APMC", "Raghogarh APMC"],
        "Gwalior": ["Gwalior APMC", "Dabra APMC", "Bhitarwar APMC"],
        "Harda": ["Harda APMC", "Khirkiya APMC", "Sirali APMC", "Timarni APMC"],
        "Hoshangabad": ["Hoshangabad APMC", "Babai APMC", "Banapura APMC", "Itarsi APMC", "Pipariya APMC", "Semri Harchand APMC"],
        "Indore": ["Indore APMC (Choithram)", "Sanwer APMC", "Mhow APMC", "Depalpur APMC", "Gautampura APMC"],
        "Jabalpur": ["Jabalpur APMC", "Patan APMC", "Sihora APMC", "Shahpura APMC"],
        "Jhabua": ["Jhabua APMC", "Petlawad APMC", "Thandla APMC"],
        "Katni": ["Katni APMC"],
        "Khandwa": ["Khandwa APMC", "Harsud APMC", "Mundi APMC", "Pandhana APMC"],
        "Khargone": ["Khargone APMC", "Sanawad APMC", "Barwah APMC", "Bikhangaon APMC", "Kasrawad APMC", "Maheshwar APMC"],
        "Mandla": ["Mandla APMC", "Bamhani APMC", "Nainpur APMC"],
        "Mandsaur": ["Mandsaur APMC", "Shamgarh APMC", "Sitamau APMC", "Bhanpura APMC", "Daloda APMC", "Garoth APMC", "Malhargarh APMC", "Suwasara APMC"],
        "Morena": ["Morena APMC", "Ambah APMC", "Jora APMC", "Kailaras APMC", "Porsa APMC", "Sabalgarh APMC"],
        "Narsinghpur": ["Narsinghpur APMC", "Gadarwara APMC", "Gotegaon APMC", "Kareli APMC", "Tendukheda APMC"],
        "Neemuch": ["Neemuch APMC", "Manasa APMC", "Jawad APMC"],
        "Panna": ["Panna APMC"],
        "Raisen": ["Raisen APMC", "Bareli APMC", "Begamganj APMC", "Gairatganj APMC", "Obedullaganj APMC", "Silwani APMC", "Udaipura APMC"],
        "Rajgarh": ["Rajgarh APMC", "Biaora APMC", "Khilchipur APMC", "Kurawar APMC", "Narsinghgarh APMC", "Pachore APMC", "Sarangpur APMC"],
        "Ratlam": ["Ratlam APMC", "Jaora APMC", "Sailana APMC", "Alot APMC", "Tal APMC"],
        "Rewa": ["Rewa APMC", "Baikunthpur APMC", "Chakghat APMC", "Hanumana APMC"],
        "Sagar": ["Sagar APMC", "Khurai APMC", "Bina APMC", "Deori APMC", "Garhakota APMC", "Rahatgarh APMC", "Rehli APMC"],
        "Satna": ["Satna APMC", "Amarpatan APMC", "Maihar APMC", "Nagod APMC", "Rampur Baghelan APMC", "Unchehara APMC"],
        "Sehore": ["Sehore APMC", "Ashta APMC", "Ichhawar APMC", "Nasrullaganj APMC", "Rehti APMC"],
        "Seoni": ["Seoni APMC", "Barghat APMC", "Keolari APMC", "Lakhnadon APMC"],
        "Shahdol": ["Shahdol APMC", "Burhar APMC"],
        "Shajapur": ["Shajapur APMC", "Akodia APMC", "Kalapipal APMC", "Moman Badodiya APMC", "Shujalpur APMC"],
        "Sheopur": ["Sheopur APMC", "Baroda APMC", "Vijaypur APMC"],
        "Shivpuri": ["Shivpuri APMC", "Badarwas APMC", "Karera APMC", "Kolaras APMC", "Magroni APMC", "Pohari APMC"],
        "Sidhi": ["Sidhi APMC", "Majhauli APMC"],
        "Singrauli": ["Waidhan APMC"],
        "Tikamgarh": ["Tikamgarh APMC", "Niwari APMC", "Palera APMC", "Prithvipur APMC"],
        "Ujjain": ["Ujjain APMC", "Khachrod APMC", "Mahidpur APMC", "Barnagar APMC", "Tarana APMC", "Unhel APMC"],
        "Umaria": ["Umaria APMC"],
        "Vidisha": ["Vidisha APMC", "Basoda APMC", "Gulabganj APMC", "Kurwai APMC", "Lateri APMC", "Sironj APMC", "Shamshabad APMC"]
    },
    "Punjab": {
        "Amritsar": ["Amritsar APMC", "Rayya APMC", "Ajnala APMC", "Majitha APMC", "Attari APMC", "Gehri APMC"],
        "Barnala": ["Barnala APMC", "Bhadaur APMC", "Dhanaula APMC", "Mehal Kalan APMC", "Tapa APMC"],
        "Bathinda": ["Bathinda APMC", "Rampura Phul APMC", "Maur APMC", "Talwandi Sabo APMC", "Bhucho APMC", "Goniana APMC", "Nathana APMC", "Sangat APMC"],
        "Faridkot": ["Faridkot APMC", "Jaitu APMC", "Kotkapura APMC"],
        "Fatehgarh Sahib": ["Fatehgarh Sahib APMC", "Amloh APMC", "Bassi Pathana APMC", "Khamario APMC", "Sirhind APMC"],
        "Ferozepur": ["Ferozepur APMC", "Zira APMC", "Guru Har Sahai APMC", "Ferozepur Cantt APMC", "Makhu APMC", "Mamdot APMC", "Talwandi Bhai APMC"],
        "Fazilka": ["Fazilka APMC", "Abohar APMC", "Jalalabad APMC"],
        "Gurdaspur": ["Gurdaspur APMC", "Batala APMC", "Dina Nagar APMC", "Dhariwal APMC", "Fatehgarh Churian APMC", "Kalanaur APMC", "Qadian APMC", "Sri Hargobindpur APMC"],
        "Hoshiarpur": ["Hoshiarpur APMC", "Dasuya APMC", "Mukerkian APMC", "Garhshankar APMC", "Tanda Urmur APMC"],
        "Jalandhar": ["Jalandhar APMC", "Phillaur APMC", "Nakodar APMC", "Shahkot APMC", "Adampur APMC", "Apra APMC", "Bhogpur APMC", "Goraya APMC", "Kartarpur APMC", "Lohian Khas APMC", "Nurmahal APMC"],
        "Kapurthala": ["Kapurthala APMC", "Phagwara APMC", "Bholath APMC", "Sultanpur Lodhi APMC"],
        "Ludhiana": ["Ludhiana APMC", "Khanna APMC", "Jagraon APMC", "Samrala APMC", "Doraha APMC", "Hathur APMC", "Koom Kalan APMC", "Machhiwara APMC", "Mullanpur Dakha APMC", "Raikot APMC", "Sahnewal APMC", "Sidhwan Bet APMC"],
        "Mansa": ["Mansa APMC", "Bareta APMC", "Bhikhi APMC", "Budhlada APMC", "Sardulgarh APMC"],
        "Moga": ["Moga APMC", "Baghapurana APMC", "Nihal Singh Wala APMC", "Dharamkot APMC", "Kot Ise Khan APMC"],
        "Muktsar": ["Muktsar APMC", "Bariwala APMC", "Gidderbaha APMC", "Malout APMC"],
        "Nawanshahr": ["Nawanshahr APMC", "Balachaur APMC", "Banga APMC"],
        "Pathankot": ["Pathankot APMC"],
        "Patiala": ["Patiala APMC", "Rajpura APMC", "Nabha APMC", "Samana APMC", "Dudhansadhan APMC", "Ghanour APMC", "Patran APMC"],
        "Rupnagar": ["Rupnagar APMC", "Anandpur Sahib APMC", "Chamkaur Sahib APMC", "Morinda APMC"],
        "Sangrur": ["Sangrur APMC", "Malerkotla APMC", "Sunam APMC", "Dhuri APMC", "Ahmedgarh APMC", "Amargarh APMC", "Bhawanigarh APMC", "Dirba APMC", "Khanauri APMC", "Lehra Gaga APMC", "Moonak APMC", "Sandhura APMC"],
        "Mohali": ["Banur APMC", "Derabassi APMC", "Kharar APMC", "Kurali APMC", "Lalru APMC"],
        "Tarn Taran": ["Tarn Taran APMC", "Bhikhiwind APMC", "Khemkaran APMC", "Naushehra Pannuan APMC", "Patti APMC"]
    },
    "Haryana": {
        "Ambala": ["Ambala City APMC", "Ambala Cantt APMC", "Naraingarh APMC", "Barara APMC", "Mullana APMC"],
        "Bhiwani": ["Bhiwani APMC", "Bawani Khera APMC", "Loharu APMC", "Siwani APMC", "Tosham APMC"],
        "Charkhi Dadri": ["Charkhi Dadri APMC", "Badhra APMC"],
        "Faridabad": ["Faridabad APMC", "Ballabgarh APMC"],
        "Fatehabad": ["Fatehabad APMC", "Tohana APMC", "Ratia APMC", "Bhattu Kalan APMC", "Jakhal APMC"],
        "Gurgaon": ["Gurgaon APMC", "Farrukhnagar APMC", "Hailey Mandi APMC", "Sohna APMC"],
        "Hisar": ["Hisar APMC", "Hansi APMC", "Barwala APMC", "Narnaund APMC", "Adampur APMC", "Uklana APMC"],
        "Jhajjar": ["Jhajjar APMC", "Bahadurgarh APMC", "Beri APMC"],
        "Jind": ["Jind APMC", "Safidon APMC", "Narwana APMC", "Julana APMC", "Pillukhera APMC", "Uchana APMC"],
        "Kaithal": ["Kaithal APMC", "Pundri APMC", "Cheeka APMC", "Kalayat APMC", "Pai APMC", "Rajound APMC", "Siwan APMC"],
        "Karnal": ["Karnal APMC", "Gharaunda APMC", "Assandh APMC", "Taraori APMC", "Indri APMC", "Jundla APMC", "Kunjpura APMC", "Nigdu APMC", "Nilokheri APMC", "Nissing APMC"],
        "Kurukshetra": ["Thanesar APMC", "Shahabad APMC", "Pehowa APMC", "Ladwa APMC", "Babain APMC", "Ismailabad APMC", "Pipli APMC"],
        "Mahendragarh": ["Mahendragarh APMC", "Narnaul APMC", "Ateli APMC", "Kanina APMC", "Nangal Choudhary APMC"],
        "Nuh": ["Nuh APMC", "Ferozepur Jhirka APMC", "Punhana APMC", "Taoru APMC"],
        "Palwal": ["Palwal APMC", "Hassanpur APMC", "Hathin APMC", "Hodal APMC"],
        "Panchkula": ["Panchkula APMC", "Barwala APMC (Panchkula)", "Raipur Rani APMC"],
        "Panipat": ["Panipat APMC", "Samalkha APMC", "Bapoli APMC", "Madlauda APMC"],
        "Rewari": ["Rewari APMC", "Bawal APMC", "Kosli APMC"],
        "Rohtak": ["Rohtak APMC", "Meham APMC", "Sampla APMC"],
        "Sirsa": ["Sirsa APMC", "Ellenabad APMC", "Dabwali APMC", "Kalanwali APMC", "Rania APMC"],
        "Sonipat": ["Sonipat APMC", "Ganaur APMC", "Gohana APMC", "Kharkhoda APMC"],
        "Yamunanagar": ["Yamunanagar APMC", "Jagadhri APMC", "Radaur APMC", "Sadhaura APMC"]
    },
    "Uttar Pradesh": {
        "Agra": ["Agra APMC", "Fatehabad APMC", "Kheragarh APMC", "Jarar APMC", "Khairagarh APMC", "Samsabad APMC"],
        "Aligarh": ["Aligarh APMC", "Khair APMC", "Atrauli APMC", "Charra APMC", "Iglas APMC"],
        "Allahabad": ["Allahabad APMC (Mundera)", "Jasra APMC", "Sirsa APMC"],
        "Ambedkar Nagar": ["Akbarpur APMC", "Tanda APMC"],
        "Amethi": ["Jais APMC", "Musafirkhana APMC"],
        "Amroha": ["Amroha APMC", "Dhanaura APMC", "Hasanpur APMC"],
        "Auraiya": ["Auraiya APMC", "Achalda APMC", "Dibiyapur APMC"],
        "Azamgarh": ["Azamgarh APMC"],
        "Baghpat": ["Baraut APMC", "Khekra APMC"],
        "Bahraich": ["Bahraich APMC", "Nanpara APMC", "Risia APMC"],
        "Ballia": ["Ballia APMC", "Rasra APMC"],
        "Balrampur": ["Balrampur APMC", "Tulsipur APMC", "Utraula APMC"],
        "Banda": ["Banda APMC", "Atarra APMC", "Baberu APMC"],
        "Barabanki": ["Barabanki APMC", "Rudauli APMC"],
        "Bareilly": ["Bareilly APMC", "Aonla APMC", "Baheri APMC", "Faridpur APMC"],
        "Basti": ["Basti APMC"],
        "Bijnor": ["Bijnor APMC", "Chandpur APMC", "Dhampur APMC", "Haldaur APMC", "Kiratpur APMC", "Najibabad APMC"],
        "Budaun": ["Budaun APMC", "Bilsi APMC", "Dataganj APMC", "Sahaswan APMC", "Ujhani APMC"],
        "Bulandshahr": ["Bulandshahr APMC", "Anupshahr APMC", "Aurangabad APMC", "Dibai APMC", "Gulaothi APMC", "Jahangirabad APMC", "Khurja APMC", "Siana APMC", "Sikandrabad APMC"],
        "Chandauli": ["Chandauli APMC"],
        "Chitrakoot": ["Karwi APMC"],
        "Deoria": ["Deoria APMC"],
        "Etah": ["Etah APMC", "Awagarh APMC", "Ganjdundwara APMC", "Kasganj APMC"],
        "Etawah": ["Etawah APMC", "Bharthana APMC", "Jaswantnagar APMC"],
        "Faizabad": ["Faizabad APMC"],
        "Farrukhabad": ["Farrukhabad APMC", "Kaimganj APMC", "Mohammadabad APMC"],
        "Fatehpur": ["Fatehpur APMC", "Bindki APMC", "Khaga APMC"],
        "Firozabad": ["Firozabad APMC", "Shikohabad APMC", "Sirslaganj APMC", "Tundla APMC"],
        "Gautam Buddha Nagar": ["Noida APMC", "Dadri APMC", "Dankaur APMC", "Jewar APMC"],
        "Ghaziabad": ["Ghaziabad APMC", "Hapur APMC", "Muradnagar APMC"],
        "Ghazipur": ["Ghazipur APMC", "Jangipur APMC", "Yusufpur APMC"],
        "Gonda": ["Gonda APMC", "Colonelganj APMC", "Nawabganj APMC"],
        "Gorakhpur": ["Gorakhpur APMC", "Chauri Chaura APMC", "Sahjanwa APMC"],
        "Hamirpur": ["Hamirpur APMC", "Maudaha APMC", "Rath APMC"],
        "Hardoi": ["Hardoi APMC", "Madhoganj APMC", "Sandila APMC", "Shahabad APMC"],
        "Jalaun": ["Jalaun APMC", "Konch APMC", "Orai APMC"],
        "Jaunpur": ["Jaunpur APMC", "Mungra Badshahpur APMC", "Shahganj APMC"],
        "Jhansi": ["Jhansi APMC", "Chirgaon APMC", "Mauranipur APMC", "Moth APMC"],
        "Kannauj": ["Kannauj APMC", "Chhibramau APMC"],
        "Kanpur": ["Kanpur APMC", "Bilhaur APMC", "Pukhrayan APMC", "Rura APMC"],
        "Lakhimpur Kheri": ["Lakhimpur APMC", "Gola Gokarnath APMC", "Mohammadi APMC", "Paliakalan APMC", "Tikonia APMC"],
        "Lucknow": ["Lucknow APMC", "Malihabad APMC"],
        "Mainpuri": ["Mainpuri APMC", "Bewar APMC", "Ghiror APMC"],
        "Mathura": ["Mathura APMC", "Kosi Kalan APMC"],
        "Meerut": ["Meerut APMC", "Sardhana APMC", "Mawana APMC"],
        "Mirzapur": ["Mirzapur APMC", "Ahirora APMC"],
        "Moradabad": ["Moradabad APMC", "Chandausi APMC", "Sambhal APMC", "Bahjoi APMC", "Bilari APMC"],
        "Muzaffarnagar": ["Muzaffarnagar APMC", "Kairana APMC", "Kandhla APMC", "Khatauli APMC", "Shamli APMC", "Thanabhawan APMC"],
        "Pilibhit": ["Pilibhit APMC", "Bisalpur APMC", "Puranpur APMC"],
        "Pratapgarh": ["Pratapgarh APMC"],
        "Rae Bareli": ["Rae Bareli APMC", "Jais APMC", "Lalganj APMC"],
        "Rampur": ["Rampur APMC", "Bilaspur APMC", "Milak APMC", "Shahabad APMC"],
        "Saharanpur": ["Saharanpur APMC", "Deoband APMC", "Gangoh APMC", "Nakur APMC", "Nanauta APMC", "Rampur Maniharan APMC", "Sultanpur APMC"],
        "Shahjahanpur": ["Shahjahanpur APMC", "Jalalabad APMC", "Powayan APMC", "Tilhar APMC"],
        "Sitapur": ["Sitapur APMC", "Biswan APMC", "Maholi APMC", "Misrikh APMC", "Sidhauli APMC"],
        "Sultanpur": ["Sultanpur APMC"],
        "Unnao": ["Unnao APMC", "Bangarmau APMC", "Purwa APMC"]
    }
};

export const commodityGroups = {
    "Cereals": ["Wheat", "Rice", "Maize", "Bajra", "Jowar", "Ragi", "Barley", "Paddy (Dhan)"],
    "Pulses": ["Gram (Chana)", "Tur (Arhar)", "Urad", "Moong", "Masur", "Peas (Matar)", "Rajmash"],
    "Oilseeds": ["Groundnut", "Mustard", "Soyabean", "Sesamum", "Sunflower", "Castor Seed", "Niger Seed", "Linseed", "Safflower"],
    "Vegetables": ["Potato", "Onion", "Tomato", "Brinjal", "Cabbage", "Cauliflower", "Okra (Bhindi)", "Green Chilli", "Ginger", "Garlic", "Lemon", "Carrot", "Radish", "Spinach", "Peas (Green)", "Bottle Gourd", "Bitter Gourd", "Cucumber", "Capsicum"],
    "Fruits": ["Mango", "Banana", "Apple", "Pomegranate", "Grapes", "Papaya", "Watermelon", "Orange", "Guava", "Pineapple", "Sapota", "Muskmelon", "Sweet Lime", "Custard Apple"],
    "Spices": ["Cumin (Jeera)", "Fennel (Saunf)", "Coriander (Dhania)", "Turmeric", "Red Chilli", "Black Pepper", "Fenugreek (Methi)", "Ajwain", "Cardamom"],
    "Fibre Crops": ["Cotton", "Jute"],
    "Commercial Crops": ["Sugarcane", "Tobacco", "Arecanut", "Coconut"]
};
